### ISSUE TITLE
Children stores event bubbling

### ISSUE THREAD

**Issue by samuelsimoes** [samuelsimoes/fluxo#21]
As discussed on https://github.com/fluxo-js/fluxo/issues/20, Fluxo will handle attributes that hold other stores and having a way to listen children events would be great to do things like this:

``` js
class Post extends Fluxo.ObjectStore {
  static computed = {
    commentsCount: ["comments:change"]
  }

  commentsCount () {
    return this.data.comments.stores.length;
  }
}
```

**Comment by sobrinho** [comment]
I would go to something like overwrite the constructor to iterate through attribute parsers or maybe create a hook on attribute parser, not sure yet.

Overwriting the constructor would be something like:

``` javascript
class Fluxo.NestedObjectStore extends Fluxo.ObjectStore {
  constructor (data, options) {
    super(data, options);

    this.constructor.attributeParsers.forEach(attribute => {
      this.data[attribute].bind("change", this.buildListenerFor(attribute));
    });
  }

  buildListenerFor (attribute) {
    return (event, ...data) => this.triggerEvent(`change:${attribute}:${event.attribute}`, ...data)
  }
}
```

The idea is listen an event on the nested store and emit an event on the main store with same data, just renaming from `change:author` to `change:comments:author`.

Although the implementation would be more complex because we must remove the listening when the store is replaced, like this:

``` javascript
class Fluxo.NestedObjectStore extends Fluxo.ObjectStore {
  constructor (data, options) {
    super(data, options);

    this.listeners = [];

    this.constructor.attributeParsers.forEach(attribute => {
      this.listeners[attribute] = this.data[attribute].bind("change", this.buildListenerFor(attribute));
      this.bind(`change:${attribute}`, this.removeListenerFor(attribute));
    });
  }

  buildListenerFor (attribute) {
    return (event, ...data) => this.triggerEvent(`change:${attribute}:${event.attribute}`, ...data)
  }

  removeListenerFor (attribute) {
    return () => this.listeners[attribute](); // assuming the interface that the bind returns a canceler
  }
}
```

**Comment by samuelsimoes** [comment]
Great, I thought this way too with a little difference that was tweak the `setAttribute` to this, like this:

``` diff
diff --git a/src/fluxo.object_store.js b/src/fluxo.object_store.js
index 3bd1c88..3dbe606 100644
--- a/src/fluxo.object_store.js
+++ b/src/fluxo.object_store.js
@@ -14,6 +14,8 @@ export default class {

     this.data = {};

+    this.storeAttributesEventsCanceler = {};
+
     this.computed = (this.constructor.computed || {});

     this.attributeParsers = (this.constructor.attributeParsers || {});
@@ -90,6 +92,24 @@ export default class {
     }
   }

+  stopListenStoreAttribute (attributeName) {
+    this.storeAttributesEventsCanceler[attribute].call();
+    delete this.storeAttributesEventsCanceler[attribute];
+  }
+
+  listenStoreAttribute (attribute, store) {
+    let onStoreEvent = function(attributeName, eventName, ...args) {
+      this.triggerEvent(`${attributeName}:${eventName}`, ...args);
+
+      if (eventName === "change") {
+        delete this.lastGeneratedJSON;
+      }
+    };
+
+    this.storeAttributesEventsCanceler[attribute] =
+      value.on(["*"], onStoreEvent.bind(this, attribute));
+  }
+
   setAttribute (attribute, value, options) {
     if (typeof attribute !== "string") {
       throw new Error(`The "attribute" argument on store's "setAttribute" function must be a string.`);
@@ -105,6 +125,14 @@ export default class {
       value = this.attributeParsers[attribute](value);
     }

+    if (this.data[attribute] instanceof ObjectStore) {
+      this.stopListenStoreAttribute(attribute);
+    }
+
+    if (value instanceof ObjectStore) {
+      this.listenStoreAttribute(attribute, value);
+    }
+
     this.data[attribute] = value;

     this.triggerEvent(`change:${attribute}`);
@@ -117,6 +145,8 @@ export default class {
   unsetAttribute  (attribute, options) {
     options = options || {};

+    this.stopListenStoreAttribute(attribute);
+
     delete this.data[attribute];

     delete this.lastGeneratedJSON;
```

**Comment by sobrinho** [comment]
Seems better although it needs a small change that `this.data[attribute]` may be a store but do not have a canceler.

That is probably an error but it's possible because the developer may want to use an attribute as a store but without using the nested store.

My first thought was to throw an error in that case but we may not need to bubble events or cast the store if we are confident enough that the system do not need this bureaucracy (i.e.: internal nested stores that is not exposed to the application for whatever).

_Note: there is some typos and missing variables on the proposed patch but I'm assuming that is a draft._

**Comment by samuelsimoes** [comment]
This feature opens a "problem", imagine computed properties that relies upon stores attributes. It may exists or not, in this situation the developer must be careful, like the example below:

``` js
class Post extends Fluxo.ObjectStore {
  static computed = {
    commentsCount: ["change:comments", "comments:change"]
  }

  commentsCount () {
    if (this.data.comments) {
      return this.data.comments.stores.length;
    } else {
      return 0;
    }
  }
}
```

We gonna do something about?

**Comment by sobrinho** [comment]
Well, if the comments hasn't been defined yet, the commentsCount won't be called at all.

If the developer explicit sets it to `null` or `undefined`, he must be aware that the computed may be called without a collection.

Makes sense?

**Comment by samuelsimoes** [comment]
Today computed properties are computed on the store construction, but I also believe that is the developer job take care if exists the possibility to a computed property that depends on some store attribute can starts null or becomes null sometime.

**Comment by sobrinho** [comment]
All of them or only the ones that the attribute was set?
1. Sets all attributes
2. Compute all computed given the previous attributes

Or:
1. Sets all attributes
2. Compute everything

Both may be correct but the former seems better.

**Comment by samuelsimoes** [comment]
Set all attributes and compute everything: https://github.com/fluxo-js/fluxo/blob/master/src/fluxo.object_store.js#L32-L36

**Comment by sobrinho** [comment]
Well, that's awkward IMO, I would prefer te set and compute only the relevant attributes :see_no_evil: 

Something like:

``` javascript
class Person {
  static computed: {
    name: ["change:fname", "change:lname"],
    age: ["change:birthdate"]
  }

  name () {
    return `${this.data.fname} ${this.data.lname}`;
  }

  age () {
    // some calculation using moment.js
  }
}

new Person({fname: "Gabriel", lname: "Sobrinho"});
```

Would do:
1. Set fname
2. Set fname
3. Compute name

An error may happen if we try to compute the age on this case because we don't have the birthdate.

To solve other cases where I want a computed to be zero, infinity or an empty array or empty object, we could listen to a new event like `store:afterInitialize`, i.e.:

``` javascript
class Inventory {
  static computed: {
    balance: ["store:afterInitialize", "change:movements"]
  }

  balance () {
    return (this.data.movements || []).reduce(movement, balance => movement.data.quantity + balance, 0);
  }
}
```

That case I want a zero instead of null, so, I explicit declare that after initialization, regardless of the movements being set or not, it should be called.

Makes sense?

**Comment by samuelsimoes** [comment]
My vision of computed properties is that it must be resilient to be called with or without its "internal dependencies". The events that triggers these computations are only specifications of when this must be recomputed.

In other words, the events of computed properties aren't dependencies declaration, but when this value should be recomputed.

So I don't like the idea of computed properties that can't be called on certain moments, but I have to say that computed properties with null values **can be** somekind of PITA, but I don't know If we need care too much about.

_Just for reference: the Ember.js, where we "copied" this feature, works this way (compute everything on construction with or not its dependencies)._

**Comment by sobrinho** [comment]
Okay, lets assume this is correct since it didn't bite us.

About the first state, assuming that there is parser, the default value of a nested store would be a empty collection store.

If the user explicit sets it to falsey, he needs to handle that, like this:

``` javascript
class Post extends Fluxo.ObjectStore {
  static computed = {
    // I think `comments:change` and `change:comments` would be easy to typo.
    // Better to use `change:comments:*` to capture any change on the nested store, easier to remember.
    commentsCount: ["change:comments", "change:comments:*"]
  }

  commentsCount () {
    if (this.data.comments) {
      return this.data.comments.stores.length;
    } else {
      return 0;
    }
  }
}
```

Although if the user do not pretends to set it to null or undefined, the if branch is not necessary because it will be always there as an empty collection.

Makes sense?

**Comment by samuelsimoes** [comment]
About the _if branch_: yes, the developer/team need know if it could become a falsy value, like we do with `allow_nil: true` on Rails delegations when we don't know if the callee is null.

About the inner comment on your snippet I agree that it can cause some confusion but I don't know about your suggestion since you can emit other events unrelated with change events on your children stores. Imagine that you trigger on your child store something like `myCustomEvent`. On the parent you will need catch this event with `change:comments:myCustomEvent` which, semantically, doesn't look good IMO.

**Comment by sobrinho** [comment]
What kind of events a store may emit that is not a change?

Since the store is a state box, do not makes any sense to emit a event that is not related to a change, no?

**Comment by samuelsimoes** [comment]
Example: you have a ToDo list where todos have an expire time, when expired the todo is removed from the list, you could use some design like this: 

``` js
class Todos extends Fluxo.CollectionStore {
  static store = Todo;

  constructor () {
    super(...arguments);
    this.on(["stores:expired"], (_, store) => this.remove(store));
  }
}

class Todo extends Fluxo.ObjectStore {
  constructor () {
    super(...arguments);
    // ... logic to run a timer and emit the `expired` event when expires
  }
}
```

Ok that we can use some attribute flag like `expired` on the example above, but we would need verify if the `expired` attribute is `true`, with a dedicated event we don't need verify since the event was created to this.

**Comment by sobrinho** [comment]
The `expired` event means a change on the todo, so it would be okay to listen to it because it has been changed.

I'm really concerned about `change:todos` and `todos:change` because I can't tell which one is correct: `todos:change:expired` vs `change:todos:expired`.

Another option would be `change:todos` be triggered when the store itself changes and the nested stores changes but that would result in a single event for two change situations.

**Comment by samuelsimoes** [comment]
Children `change` triggering parent's `change:<store>` could help on this case, I believe it can't cause any harm...

**Comment by samuelsimoes** [comment]
The draft patch with the modifications that we talked about:

``` patch
diff --git a/src/fluxo.object_store.js b/src/fluxo.object_store.js
index 6f60876..a2f8315 100644
--- a/src/fluxo.object_store.js
+++ b/src/fluxo.object_store.js
@@ -14,6 +14,8 @@ export default class {

     this.data = {};

+    this.storeAttributesEventsCanceler = {};
+
     this.computed = (this.constructor.computed || {});

     this.attributeParsers = (this.constructor.attributeParsers || {});
@@ -90,6 +92,30 @@ export default class {
     }
   }

+  stopListenStoreAttribute (attributeName) {
+    this.storeAttributesEventsCanceler[attributeName].call();
+    delete this.storeAttributesEventsCanceler[attributeName];
+  }
+
+  listenStoreAttribute (attribute, store) {
+    let onStoreEvent = function(attributeName, eventName, ...args) {
+      if (eventName.indexOf("change:") === 0) {
+        this.triggerEvent(`change:${attributeName}:${eventName.substring(7)}`, ...args);
+      } else if (eventName !== "change") {
+        this.triggerEvent(`change:${attributeName}:${eventName}`, ...args);
+      }
+
+      if (eventName === "change" || eventName === "stores:change") {
+        this.triggerEvent(`change:${attribute}`);
+        this.triggerEvent(`change`);
+        delete this.lastGeneratedJSON;
+      }
+    };
+
+    this.storeAttributesEventsCanceler[attribute] =
+      store.on(["*"], onStoreEvent.bind(this, attribute));
+  }
+
   setAttribute (attribute, value, options) {
     if (typeof attribute !== "string") {
       throw new Error(`The "attribute" argument on store's "setAttribute" function must be a string.`);
@@ -105,6 +131,14 @@ export default class {
       value = this.attributeParsers[attribute](value);
     }

+    if (this.data[attribute] instanceof this.constructor) {
+      this.stopListenStoreAttribute(attribute);
+    }
+
+    if (value instanceof this.constructor) {
+      this.listenStoreAttribute(attribute, value);
+    }
+
     this.data[attribute] = value;

     this.triggerEvent(`change:${attribute}`);
@@ -117,6 +151,10 @@ export default class {
   unsetAttribute  (attribute, options) {
     options = options || {};

+    if (this.data[attribute] instanceof this.constructor) {
+      this.stopListenStoreAttribute(attribute);
+    }
+
     delete this.data[attribute];

     delete this.lastGeneratedJSON;
```

**Comment by sobrinho** [comment]
Seems nice, open the pull request and lets do it!

**Comment by samuelsimoes** [comment]
Done :)
