### ISSUE TITLE
Collection store not sorting when update a children store

### ISSUE THREAD

**Issue by samuelsimoes** [samuelsimoes/fluxo#27]
When the attribute used to sort the collection store is changed on some children store the collection store doesn't reorder itself.

**Comment by sobrinho** [comment]
Yes, makes sense.

The current implementation is very rudimentar, just the basic sort.

Are you thinking in listen the `change:$attribute` to reorder?

**Comment by sobrinho** [comment]
I vaguely remember that add stores, reset and etc wasn't resorting either.

**Comment by samuelsimoes** [comment]
Today only the `add` method reorders the collection. About your suggestion to listen to the attribute to make the ordering I agree, but what API we would use?

Something like this below?

``` js
class Foo extends CollectionStore {
  static sort = {
    on: ["stores:change:name"],
    resolve: ((a, b) => a.data.order - b.data.order)
  };
}
```

**Comment by sobrinho** [comment]
Can't we just call the order method again (just like backbone)?

This means we would listen to change instead of change:attr.

Performance would be worse but until someone is using thousands of stores, we may not need to worry.

**Comment by samuelsimoes** [comment]
Ok. Listening to the collection `change` could the job. 👌  I will submit a patch soon.
