### ISSUE TITLE
Remove stores on setStores method

### ISSUE THREAD

**Issue by samuelsimoes** [samuelsimoes/fluxo#28]
When you have a list that is constantly feed by a pooling, for example, is a common pattern do this to update the list:

``` js
this.collection.resetStores([...payload...]);
```

But sometimes many of these stores from payload was added before the `removeAll`, so we spend resources allocating new objects and doing the setup for stores that were added before just because the "reset".

Besides this, on other situations you may set some attribute relevant only on the interface context and with the reset you lost this state.

My proposal: `setStores` could have some flag to update the already added stores and remove the collection stores that aren't present on payload, something like: 
`setStores([...], { removeMissing: true })`.

What do you think?

**Comment by sobrinho** [comment]
Seems to makes sense :shipit:
