### ISSUE TITLE
Refactor to use ES6 features and recommend es6-shim

### ISSUE THREAD

**Issue by sobrinho** [samuelsimoes/fluxo#3]
What you think about that?

I have to check the source but I believe we are already using some functions which aren't available at all browsers, what [es6-shim](https://github.com/paulmillr/es6-shim) does.

**Comment by samuelsimoes** [comment]
I agree, but include a hole shim package won't increase the lib height? There is some transpiler like Babel to this task? To only include/transpile what we have on our code. Remembering that we also have some ES5 features (like bind).

I know that https://github.com/zloirock/core-js allows include (using node syntax) the needed shims, but something like a transpiler that we don't need care about would be the perfect solution to me.

**Comment by sobrinho** [comment]
Babel only transpiles the syntax, i.e.:

``` javascript
function x () { }

x.bind(null);
```

``` javascript
"use strict";

function x() {}

x.bind(null);
```

You can check it [here](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=function%20x%20%28%29%20%7B%20%7D%0A%0Ax.bind%28null%29%3B).

The thing is that bind isn't available everywhere like a lot of other functions that es6-shim makes available.

**Comment by samuelsimoes** [comment]
ES6 features are transpiled for ES5 code via Babel. About the ES5 shims should we worry about this? As far I know everything that we use is widely supported by IE9+.

**Comment by sobrinho** [comment]
Yeah, I think we can close that.
