### ISSUE TITLE
Mutating prototype warning

### ISSUE THREAD

**Issue by LucasArruda** [samuelsimoes/fluxo#38]
Hi!

I'm using fluxo but I'm getting the current warning:

```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
```

I checked the code and I think the culprit probably is:
`Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass;`
which can be found here https://github.com/fluxo-js/fluxo/blob/master/dist/fluxo.js#L19

The suggestion is to use `Object.create()` -> http://stackoverflow.com/a/23809148

I could help if needed.

Thanks!

**Comment by samuelsimoes** [comment]
Thanks for your report.

After a quick search, I found that it's a problem with Firefox and Babel transpiled code. Looks like other folks are getting this error too https://github.com/zenorocha/clipboard.js/issues/141#issuecomment-190981540

So, apparently we don't have too much to do about this besides getting rid of ES6 classes with Babel.js, which will not happen. 😕 

I'll let this open to future checks if Babel's team found some solution or something changed in Firefox.

**Comment by LucasArruda** [comment]
@samuelsimoes thanks for the reply! 
Then I should close it.
