### ISSUE TITLE
Exception: this.attributeParsers[attribute] is not a function

### ISSUE THREAD

**Issue by fnmunhoz** [samuelsimoes/fluxo#39]
Hello!

We are using Fluxo v0.0.16 and we started to get an error after the recent release of Google Chrome version 51. The error didn't happened with Google Chrome version 50.

Unfortunately, I couldn't figure out the reason yet. 

The error occurs on this line https://github.com/fluxo-js/fluxo/blob/v0.0.16/dist/fluxo.js#L165 with the following message: `Uncaught TypeError: this.attributeParsers[attribute] is not a function`

Any ideas?

If there is any information that I could provide, please let me know.

Thanks!

**Comment by sobrinho** [comment]
Got it, working on this.

**Comment by sobrinho** [comment]
That is an issue on v0.0.16, latest version is already fixed ❤️

**Comment by fnmunhoz** [comment]
@sobrinho thanks!

**Comment by fnmunhoz** [comment]
For the ones who cannot upgrade to the latest version of Fluxo immediately, a workaround is to fix the problematic initialization of `attributeParsers` here: https://github.com/fluxo-js/fluxo/blob/v0.0.16/dist/fluxo.js#L142

Change this line from:

`attributeParsers: function() {},`

to:

`attributeParsers: {},`

The `attributeParsers` property should be an object and not a function.

This problem is already fixed on the latest version of Fluxo (v0.0.23).
