### ISSUE TITLE
Error on toJSON dump when a computed property returns undefined

### ISSUE THREAD

**Issue by fnmunhoz** [samuelsimoes/fluxo#40]
Fluxo `v0.0.23` is breaking when a computed property returns `undefined`.

The following code reproduces the error:

```
js
class Person extends Fluxo.ObjectStore {
  static computed = { something: ["change"] };

  something () {
    return undefined;
  }
}

x = new Person
x.toJSON()
```

The error message is: `Uncaught SyntaxError: Unexpected token u in JSON at position 0`

The error occurs on this line: https://github.com/fluxo-js/fluxo/blob/master/dist/fluxo.js#L572

Let me known if I can help. Thanks!

**Comment by sobrinho** [comment]
Fixed by 5a4c943442a98b0fee8f0fc7ada5a50f040d7743
