### ISSUE TITLE
Remove Subsets in favor of just Computed Properties

### ISSUE THREAD

**Issue by samuelsimoes** [samuelsimoes/fluxo#42]
The [subset feature](https://github.com/fluxo-js/fluxo#collection-subsets) was well-intentioned, but now, using more, I believe that the computed properties could do this job pretty well.

Why Remove:
- Simplify the cognitive load of having two very similar concepts (computed and subset).
- Simplify the Fluxo's code removing an "almost duplicate" feature.
## Migrating

The migration should be almost totally painless, you just need to pass all your subsets declarations to `computed` class's static property upon the `add`, `remove`, `change` and/or any other dependent events and delete the `subset` key .

You will also need to change any possible `this.subsets.<my-subset>` accesses to `this.data.<my-subset>`. Remember that this attribute will no longer be a `Fluxo.CollectionStore` like it was before with the subsets feature.

**Comment by sobrinho** [comment]
Code examples from before and after?

**Comment by samuelsimoes** [comment]
Before:

``` js
class People extends Fluxo.CollectionStore {
  static subset = {
    online: ["add", "remove", "change:stores:online"]
  };

  online () {
    return this.where({ online: true });
  }
}
```

After:

``` js
class People extends Fluxo.CollectionStore {
  static computed = {
    online: ["add", "remove", "change:stores:online"]
  };

  online () {
    return this.where({ online: true });
  }
}
```

In this case I just changed the `subset` property to `computed`, simple as that. :)

**Comment by samuelsimoes** [comment]
Thinking better about this we might have a very specific problem with equality checks that I don't know if it's exactly a problem.

Look at this case with the **current subset implementation**:

``` js
class People extends Fluxo.CollectionStore {
  static subset = {
    online: ["add", "remove", "change:stores:online"]
  };

  online () {
    return this.where({ online: true });
  }
}

let people = new People([{ id: 1, online: true }, { id: 2, online: false }]);

let json = people.toJSON();

json.stores[0] === json.online[0] // true
```

Look at the equality check on the snippet's end. Why this occurs? Because today the `Fluxo.CollectionStore#toJSON` invokes the `toJSON` on the internal subset `Fluxo.CollectionStore` and it gets the `toJSON` of its children and these children return the same JSON since it was memoized (https://github.com/fluxo-js/fluxo/blob/6d62ea59e00ee75e70bc46d659dcdd3f111c4af3/src/fluxo.collection_store.js#L416-L424).

This is particularly good when you have some kind of equality check condition to do expensive tasks like what React's pure render mixin does.

Now, the computed are simpler on its JSON dump logic. It just passes through a `JSON.stringiy` trick that always will return a new copy of its children, making impossible some sort of "pure render" with a "computed subset".

``` js
class People extends Fluxo.CollectionStore {
  static computed = {
    online: ["add", "remove", "change:stores:online"]
  };

  online () {
    return this.where({ online: true });
  }
}

let people = new People([{ id: 1, online: true }, { id: 2, online: false }]);

let json = people.toJSON();

json.stores[0] === json.online[0] // false
```

So, now I'm in doubt. 😖

**Comment by sobrinho** [comment]
Not sure, too trickier to rely on that, using deep equal will result in true which is good enough :)

**Comment by samuelsimoes** [comment]
Ok, I agree with you.

I just have a little observation out of this issue scope, but worth to mention: we'll need to "fix" the generated object by `toJSON` because today the current result would be something like: 

_It is a "pseudo JSON" where `arrayX` and `jsonX` are the "object type + version"_

```
// first toJSON
json1{
  searchTerm: "samuel"
  filtered: array1[json1{id:1}, json2{id:2}],
  stores: array1[json1{id:1}, json2{id:2}, json3{id:3}]

}

// second toJSON after change the "searchTerm"
json2{
  searchTerm: "samuel s",
  filtered: array2[json3{id:1}, json4{id:2}],
  stores: array2[json1{id:1}, json2{id:2}, json3{id:3}]
}
```

Take a look that the inner objects inside the second generated JSON `stores` key are the same of the first JSON and the inner objects inside the `filtered` key are new copies. **To normalize this I believe that we need to return new copies on the `stores` key too** because the people will know that `toJSON` always returns a deep new copy (when the store change, because actually we make internal memoization).
