### ISSUE TITLE
Quick dumb collections

### ISSUE THREAD

**Issue by samuelsimoes** [samuelsimoes/fluxo#43]
Sometimes we just want a dumb collection that parses it's children stores with some object store class without the need of declare this dumb collection class just to declare the children store class, like:

``` js
// Person class code omited
class People extends Fluxo.CollectionStore {
  static store = Person;
}
```

Would be nice if Fluxo could understand something like this:

``` js
var people = new Fluxo.CollectionStore([...], { store: Person });
people.addStore({ name: "Samuel" });
people.stores[0] // => a Person class instance.
```

**Comment by sobrinho** [comment]
As we spoke on Skype, we need a third argument as options to not pollute or mutate the data, i.e.:

``` js
var people = new Fluxo.CollectionStore(null, null, { store: Person });
people.addStore({ name: "Samuel" });
people.stores[0] // => a Person class instance.
```

**Comment by samuelsimoes** [comment]
👌 totally agree.
