### ISSUE TITLE
Subsetting

### ISSUE THREAD

**Issue by samuelsimoes** [samuelsimoes/fluxo#8]
Sometimes we need present on the interface collections subsets (eg.: online users) and to make this we have two options:
1. Put this filter on view layer. This approach can be problematic when the subset logic is complex, leak these details on the components make difficulty the creation of dumb components since it knows some internal data details.
2. Compute an attribute on the collection with the subset, but the collection's  `toJSON` doesn't handle properly on this situation returning an array with Fluxo store objects instead an array with stores `toJSON`. Eg.:

``` js
var users = Fluxo.CollectionStore.create({
  computed: {
    online: ["add", "remove", "stores:change:online"]
  },

  online: function () {
    return this.where({ online: true });
  }
});
```

We can call the `toJSON` on the `online` method, but these kind of details isn't elegant.

So I thought on the creation of a subsetting feature, the first interface that came to my mind is something like this, something very close that we have today with computed properties, but dedicated to this.

``` js
var users = Fluxo.CollectionStore.create({
  subset: {
    online: ["stores:change:online"]
  },

  online: function () {
    return this.where({ online: true });
  }
});
```

So: 
1. The subset will be stored on the `this.data.online`.
2. It'll be a fluxo collection.
3. The `users#toJSON` will call the `toJSON` on the stores of `online` subset.
4. The subset always is recomputed on `add` and `remove`, so there's no need to declare these events to recompute the subset.
5. When the subset changes it fires up the `change:<SUBSET-NAME>` event.

``` js
users.addStores([{ name: "foo", online: true }, { name: "bar", online: false }]);
users.toJSON();
// returns...
{
  cid: "FS:1",
  stores: [{ cid: "FS:2", name: "foo", online: true }, { cid: "FS:2", name: "bar", online: false }],
  online: [{ cid: "FS:2", name: "foo", online: true }]
}
```

**Comment by sobrinho** [comment]
Agreed :+1:

**Comment by samuelsimoes** [comment]
merged https://github.com/fluxo-js/fluxo/commit/08154a3fb24120cbc6c2e1ad907763861020309b
