### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by sobrinho** [samuelsimoes/fluxo#9]
Would be nice to have default values like this:

``` javascript
MyStore = Fluxo.CollectionStore.extend({
  defaults: {
    someFilter: true,
    anotherFilter: {}
  }
});
```

Note that in store constructor we need to deep clone the defaults to avoid mutating the defaults object itself.

Backbone did a different approach which I don't like (isn't obvious that it need to be that way until you find a obscure bug):

``` javascript
MyModel = Backbone.Model.extend({
  defaults: function () {
    return {
      someFilter: true,
      anotherFilter: {}
    };
  }
});
```

Although using function is a must because we may need to use `new Date()` for example:

``` javascript
MyStore = Fluxo.CollectionStore.extend({
  defaults: function () {
    return {
      someFilter: new Date,
      anotherFilter: {}
    };
  }
});
```

Using classes it would be a static property:

``` javascript
class MyStore extends Fluxo.CollectionStore {
}

MyStore.defaults = { ... };
```

**Comment by sobrinho** [comment]
Using classes it would be a static property:

``` javascript
class MyStore extends Fluxo.CollectionStore {
}

MyStore.defaults = { ... };
```

**Comment by samuelsimoes** [comment]
:ok_hand:

**Comment by sobrinho** [comment]
See #11
